# Build examples with Platformio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO 6.1.18 Arduino CI

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - 'doc/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ["Arduino", "IDF"]
        no_gfx: ["", -DNO_GFX]
#       no_fast_functions: ["", -DNO_FAST_FUNCTIONS]
#       no_cie1931: ["", -DNO_CIE1931]
#       virtual_panel: ["", -DVIRTUAL_PANE]
        example:
          - "examples/PIO_TestPatterns"
#        exclude:
#          - no_fast_functions: ""
#            virtual_panel: -DVIRTUAL_PANE

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
        enable-cache: false
    - name: Install dependencies
      run: |
        uv pip install --system platformio
    - name: Run PlatformIO CI (Arduino)
      if: ${{ matrix.framework == 'Arduino'}}
      env: 
        PLATFORMIO_BUILD_FLAGS: ${{ matrix.no_gfx }} ${{ matrix.no_fast_functions }} ${{ matrix.no_cie1931 }} ${{ matrix.virtual_panel }}
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
      run: pio ci -e esp32 -c ${{ matrix.example }}/platformio.ini
    - name: Run PlatformIO CI (ESP-IDF)
      if: ${{ matrix.framework == 'IDF'}}
      env: 
        PLATFORMIO_BUILD_FLAGS: -DIDF_BUILD ${{ matrix.no_gfx }} ${{ matrix.no_fast_functions }} ${{ matrix.no_cie1931 }} ${{ matrix.virtual_panel }}
      # pio ci doesn't use our sdkconfig, so we have to use pio run
      #run: pio run -d ${{ matrix.example }} -e esp32idf -c ${{ matrix.example }}/platformio.ini
      run: pio run -d ${{ matrix.example }}
